exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "PluginHub/Plugins/"

title: SE Plugin Loader
description: A tool to load plugins for Space Engineers automatically
permalink: /:categories/:title

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"