exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "PluginHub/Plugins/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"